---
title: "assignment_task1.2"
author: "Amalia S."
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,comment=NA,attr.source='.numberLines')

rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
```

```{r defineconnection}
my_connection <- dbConnect(SQLite(),"ecommerce.db")
```


```{sql connection=my_connection}
DROP TABLE IF EXISTS user;
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS user(
  user_id INT,
  user_first_name VARCHAR(30) NOT NULL,
  user_last_name VARCHAR(30) NOT NULL,
  user_email VARCHAR(100) NOT NULL UNIQUE,
  user_password VARCHAR(20) NOT NULL,
  user_mobile_number TEXT NOT NULL UNIQUE,
  user_membership_status VARCHAR(20) NOT NULL,
  address_id INT,
  PRIMARY KEY (user_id),
  FOREIGN KEY (address_id) REFERENCES address(address_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS address(
  address_id INT,
  user_id INT,
  address_city VARCHAR(30) NOT NULL,
  address_country VARCHAR(30) NOT NULL,
  address_state VARCHAR(20) NOT NULL,
  address_postcode VARCHAR(20) NOT NULL,
  address_type VARCHAR(20) NOT NULL,
  PRIMARY KEY (address_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
)
```


```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS product(
  product_id INT,
  product_description VARCHAR(100) NOT NULL UNIQUE,
  product_code VARCHAR(20) NOT NULL UNIQUE,
  category_id INT,
  product_stock INT NOT NULL,
  product_price INT NOT NULL,
  product_name VARCHAR(30) NOT NULL,
  product_brand VARCHAR(30),
  product_weight INT NOT NULL,
  product_dimensions INT NOT NULL,
  product_published_datetime DATE NOT NULL,
  product_average_star_ratings DOUBLE(3,2),
  product_reviews VARCHAR(50),
  PRIMARY KEY (product_id),
  FOREIGN KEY (category_id) REFERENCES product_category(category_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS product_category(
  category_id INT,
  category_name VARCHAR(30) NOT NULL UNIQUE,
  category_description VARCHAR(100) NOT NULL,
  PRIMARY KEY (category_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS seller(
  seller_id INT,
  seller_name VARCHAR(20) NOT NULL UNIQUE,
  product_id INT,
  seller_address VARCHAR(50) NOT NULL,
  seller_delivery_method VARCHAR(20) NOT NULL,
  PRIMARY KEY (seller_id),
  FOREIGN KEY (product_id) REFERENCES product(product_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS order_details(
  order_detail_id INT,
  product_id INT,
  order_qty INT NOT NULL,
  order_price INT NOT NULL,
  order_status VARCHAR(30) NOT NULL,
  order_datetime DATETIME,
  user_id INT,
  payment_id INT,
  seller_id INT,
  delivery_id INT,
  PRIMARY KEY (order_detail_id),
  FOREIGN KEY (product_id) REFERENCES product(product_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (payment_id) REFERENCES payment(payment_id),
  FOREIGN KEY (seller_id) REFERENCES seller(seller_id),
  FOREIGN KEY (delivery_id) REFERENCES delivery(delivery_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS payment(
  payment_id INT,
  payment_datetime DATETIME,
  payment_method VARCHAR(20) NOT NULL,
  payment_amount INT NOT NULL,
  user_id INT,
  order_detail_id INT,
  PRIMARY KEY (payment_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (order_detail_id) REFERENCES order_details(order_detail_id)
)
```


```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS delivery(
  delivery_id INT,
  delivery_type VARCHAR(20) NOT NULL,
  delivery_status VARCHAR(20) NOT NULL,
  delivery_datetime DATETIME,
  address_id INT,
  user_id INT,
  order_detail_id INT,
  shipper_id INT,
  PRIMARY KEY (delivery_id),
  FOREIGN KEY (address_id) REFERENCES address(address_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (order_detail_id) REFERENCES order_details(order_detail_id),
  FOREIGN KEY (shipper_id) REFERENCES shipper(shipper_id)
)
```

```{sql connection=my_connection}
CREATE TABLE IF NOT EXISTS shipper(
  shipper_id INT,
  shipper_company_name VARCHAR(20) NOT NULL UNIQUE,
  shipper_contact VARCHAR(20) NOT NULL,
  PRIMARY KEY (shipper_id)
)
```

```{sql connection=my_connection}
INSERT INTO user (user_id, user_first_name, user_last_name, user_email, user_password, user_mobile_number, user_membership_status, address_id) VALUES (1, "Amalia", "Sulwan", "amaliasharfina@gmail.com", "123456", "081111111188", "Prime", "1");
```

```{sql connection=my_connection}
INSERT INTO user (user_id, user_first_name, user_last_name, user_email, user_password, user_mobile_number, user_membership_status, address_id) VALUES (2, "Amalia", "Sulwan", "amaliasharfina2@gmail.com", "123456", "081111111199", "Prime", "2");
```
